Add support for AzureDefaultCredential-based auth
jgroups-extras/jgroups-azure pull request #178
Opened 2024-05-17 09:44 UTC by headcr4sh

Unfortunately, this PR contains a lot more changes than initially intended.
Seems like the coordinates of the Azure Storage Client library have changed and the API of the implementation was completely overhauled as well.

I took the time to try and adhere to current best practices when working with the Azure SDK for Java, e.g. utilizing the bills-of-material (BOM) dependency to make sure that all Azure-related libraries fit together, nicely.

I did not (yet) test the new library in my Cloud environment, but wanted to get this drafted PR out of the door as soon as possible to gather some feedback from the original maintainer.

@rhusar 

Closes: #177

2024-05-17 09:45 UTC, headcr4sh commented on azure/src/test/java/org/jgroups/protocols/azure/AZURE_PINGDiscoveryTest.java
> -        channel.getProtocolStack().getProtocols().replaceAll(protocol -> {
Just an automatic conversion that my IDE performed to use "try-with-resources".

2024-05-17 09:47 UTC, headcr4sh commented on pom.xml
>          <!-- Overridden versions as managed by WildFly -->
I did not check if the updated Azure SDK components still cause issues here or (worse) in other parts of the dependency tree....

2024-05-17 10:04 UTC, rhusar commented
Upon a brief look the changes look pretty good to me! Excellent work.

So what I think I will do, is that I ll move to new major branch as this bumps the SDK, pull your changes in, polish and test.

2024-11-28 11:55 UTC, R3d-Dragon commented
Any updates regarding the integration of the changes?  Can we support you somehow @rhusar ? :)

2024-11-28 11:56 UTC, rhusar commented
> Any updates regarding the integration of the changes? Can we support you somehow @rhusar ? :)

Sorry for the delays on this, will prioritize this again.

2025-01-13 07:01 UTC, R3d-Dragon commented
Good morning and happy new year!
i don't want to bother you but are there any updates regarding the integration of the PR ? :)

2025-01-13 19:40 UTC, rhusar commented
Happy new year to you too @R3d-Dragon !

Again, sorry about the delays, I got pulled into other priorities. I intend to work in this  (jgroups-extras) space this week, so I will hopefully get to finishing this. I ll keep you posted.

2026-04-11 16:12 UTC, rhusar requested changes
I am testing the changes and they do not work, the URI is not constructed correctly.

```
[ERROR] org.jgroups.protocols.azure.AZURE_PINGDiscoveryTest.testDiscovery -- Time elapsed: 0.004 s <<< ERROR!
java.lang.IllegalArgumentException: Expected authority at index 8: https://
	at java.base/java.net.URI.create(URI.java:906)
	at com.azure.storage.blob.BlobServiceAsyncClient.<init>(BlobServiceAsyncClient.java:120)
	at com.azure.storage.blob.BlobServiceClientBuilder.buildAsyncClient(BlobServiceClientBuilder.java:159)
	at com.azure.storage.blob.BlobServiceClientBuilder.buildClient(BlobServiceClientBuilder.java:116)
	at org.jgroups.protocols.azure.AZURE_PING.init(AZURE_PING.java:96)
	at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:807)
	at org.jgroups.stack.ProtocolStack.setup(ProtocolStack.java:443)
	at org.jgroups.JChannel.init(JChannel.java:916)
	at org.jgroups.JChannel.<init>(JChannel.java:128)
	at org.jgroups.JChannel.<init>(JChannel.java:109)
	at org.jgroups.protocols.azure.AZURE_PINGDiscoveryTest.create(AZURE_PINGDiscoveryTest.java:107)
	at org.jgroups.protocols.azure.AZURE_PINGDiscoveryTest.discover(AZURE_PINGDiscoveryTest.java:86)
	at org.jgroups.protocols.azure.AZURE_PINGDiscoveryTest.testDiscovery(AZURE_PINGDiscoveryTest.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.net.URISyntaxException: Expected authority at index 8: https://
	at java.base/java.net.URI$Parser.fail(URI.java:2976)
	at java.base/java.net.URI$Parser.failExpecting(URI.java:2982)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3226)
	at java.base/java.net.URI$Parser.parse(URI.java:3177)
	at java.base/java.net.URI.<init>(URI.java:623)
	at java.base/java.net.URI.create(URI.java:904)
	... 40 more

[INFO] Running org.jgroups.protocols.azure.AZURE_PINGConfigurationTest
```

2026-04-11 16:13 UTC, rhusar commented
I will submit an update with the updated SDK, since they relocated it again...

2026-04-11 16:13 UTC, closed without merging

2026-04-11 18:33 UTC, rhusar commented
Superseded by https://github.com/jgroups-extras/jgroups-azure/pull/247

2026-04-11 18:36 UTC, rhusar commented on azure/src/main/java/org/jgroups/protocols/azure/AZURE_PING.java
> +    private static final Duration TIMEOUT = Duration.ofSeconds(1);
Also, this is extremely aggressive and could cause failures with larger containers